version: 2.1
executors:
  frontend_exector:
    docker:
      - image: circleci/node:14.15.4

jobs:
  build-01:
    executor: frontend_exector
    steps:
      - checkout
      - run: echo "hello world 01"
  build-02:
    executor: frontend_exector
    steps:
      - checkout
      - run: echo "hello world 02"

